spring:
  redis:
    # 哨兵模式集群配置
    #    password:
    #    sentinel:
    #      master: mymaster
    #      nodes: 127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381
    database: 0
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
