server:
  port: 8080
  servlet:
    context-path: /springboot-shiro
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost/local1?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
